# Generated by Django 4.2.1 on 2023-05-18 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                ("member_id", models.AutoField(primary_key=True, serialize=False)),
                ("account", models.CharField(max_length=100, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("birthday", models.DateField()),
                ("hitutor_account", models.CharField(max_length=100)),
                ("hitutor_password", models.CharField(max_length=100)),
                ("email_address", models.CharField(max_length=100)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("note", models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name="Booking_Schedule",
            fields=[
                (
                    "booking_schedule_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("teacher_name", models.CharField(max_length=100)),
                ("teacher_id", models.IntegerField(default=0)),
                ("purchaseOrderId", models.IntegerField(default=0)),
                ("lessonId", models.IntegerField(default=0)),
                ("teachingType", models.IntegerField(default=0)),
                ("booking_start_time", models.DateTimeField(null=True)),
                ("booking_end_time", models.DateTimeField(null=True)),
                ("booking_status", models.BooleanField(null=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("note", models.TextField(blank=True)),
                (
                    "member_id",
                    models.ForeignKey(
                        db_column="member_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_schedules",
                        to="bookingSystem.member",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("member_id", "booking_start_time", "booking_end_time")
                },
            },
        ),
    ]
