# Generated by Django 4.2.1 on 2023-05-18 09:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookingSystem", "0003_booking_schedule_vaild"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking_schedule",
            old_name="vaild",
            new_name="valid",
        ),
    ]
