# Generated by Django 4.2.1 on 2023-05-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingSystem', '0008_booking_schedule_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
